import importlib.resources
from typing import TYPE_CHECKING

import imageio.v3 as iio
import PySide6.QtWidgets
import PySide6.QtCore
import PySide6.QtGui
import rendercanvas.qt
import pygfx as gfx
import numpy as np
import pylinalg as la

if TYPE_CHECKING:
    from .. import application


# TODO:
#   - Add built in ECI basis in bottom right.
#   - Visible Sun for scene.
class OrbitRenderer(PySide6.QtWidgets.QWidget):
    """
    Render engine for the orbital scene.
    """

    space_pressed = PySide6.QtCore.Signal()

    def __init__(self, sim):
        super().__init__()

        self.orbit_display_mode: str = "both"
        self.horizon_display_mode: str = "period"
        self.custom_horizon: int = 24 * 3600  # Defaults to one day.
        self.sim: application.SimManager = sim
        self.objects : dict[str, gfx.WorldObject] = {}

        # Set up the internal pygfx rendering via a QRenderWidget. This is placed inside a normal QWidget so that UI
        # can be overlaid on the rendering. The involves the standard pygfx pipeline of canvas -> renderer -> scene ->
        # camera -> camera controller.
        self._canvas = rendercanvas.qt.QRenderWidget()
        self._renderer = gfx.WgpuRenderer(self._canvas)
        self._scene = gfx.Scene()

        self._camera = gfx.PerspectiveCamera(fov=50, aspect=16/9)
        self._camera.local.position = (20000, 0, 0)
        self._controller = gfx.OrbitController(
            self._camera,
            register_events=self._renderer,
        )  # Add mouse control to camera.
        self._camera.show_pos((0, 0, 0), up=(0, 0, 1))

        # Add some basic objects to the scene - lighting, the Earth, and a background skybox.
        self._scene.add(gfx.AmbientLight(intensity=0.1))
        sunlight = gfx.DirectionalLight(intensity=1.25)
        sunlight.local.position = (100000, 0, 0)  # Sun points along Vernal equinox.
        self._scene.add(sunlight)

        earth_mat = gfx.MeshPhongMaterial(shininess=5)
        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/earth_texture_map.jpg").open("rb") as f:
            earth_img = iio.imread(f)
            earth_img = np.ascontiguousarray(np.flipud(earth_img))  # Need to flip array.
        earth_mat.map = gfx.Texture(earth_img, dim=2)

        self.objects["earth"] = gfx.Mesh(
            gfx.sphere_geometry(radius=6371, width_segments=64, height_segments=32),
            earth_mat
        )
        self.base_earth_rotation = la.quat_from_euler(
            (np.pi / 2, 0, 0), order="XYZ"
        )  # Rotate Earth since texture is 90 deg offset about x-axis, then offset terminator in new body frame.
        self.objects["earth"].local.rotation = self.base_earth_rotation
        self._scene.add(self.objects["earth"])

        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/skybox/skybox_right1.png").open("rb") as f:
            skybox_right1_img = iio.imread(f)
        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/skybox/skybox_left2.png").open("rb") as f:
            skybox_left2_img = iio.imread(f)
        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/skybox/skybox_top3.png").open("rb") as f:
            skybox_top3_img = iio.imread(f)
        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/skybox/skybox_bottom4.png").open("rb") as f:
            skybox_bottom4_img = iio.imread(f)
        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/skybox/skybox_front5.png").open("rb") as f:
            skybox_front5_img = iio.imread(f)
        with importlib.resources.files("hohmannpy.resources").joinpath("gfx/skybox/skybox_back6.png").open("rb") as f:
            skybox_back6_img = iio.imread(f)

        skybox_img = np.stack(
            [skybox_right1_img, skybox_left2_img, skybox_top3_img,
             skybox_bottom4_img, skybox_front5_img, skybox_back6_img],
            axis=0
        )  # Stack the faces.

        width = skybox_img.shape[1]
        height = skybox_img.shape[2]
        skybox = gfx.Background(
            None,
            gfx.BackgroundSkyboxMaterial(map=gfx.Texture(skybox_img, dim=2, size=(width, height, 6))),
        )

        self._scene.add(skybox)
        self._canvas.request_draw(self.animate)  # Render the initial scene.

        # Displaying orbits is optimized (although poorly) for large satellite constellations, although individual
        # satellites can also be rendered with no issues. To do this, all orbits are rendered via a single pygfx.Line
        # object. This pygfx.Line takes in a pygfx.Geometry which is formed from a vertical collocation of the
        # trajectories of every satellite. This is less intensive on the GPU then having a separate Line for every
        # orbit.
        #   In addition, to avoid choppiness for short time horizons the orbit trajectories generated by the
        # Mission are converted into splines (although this takes place in the SimulationManager) and then these splines
        # are used to generate denser trajectory arrays. The density is determined by the number of satellites,
        # density = 1 implies that the dense trajectory has a position index every second.
        if len(self.sim.satellites.values()) < 100:
            density = 1
        elif len(self.sim.satellites.values()) < 1000:
            density = 10
        else:
            density = 100

        self.positions = {}  # Store the dense trajectories of each satellite in a dict.
        self.dense_times = np.arange(
            0,
            self.sim.final_sim_time,
            density
        )

        # First create the trajectories as chunks which are then stacked once all have been created. This is much faster
        # than constantly appending to a growing buffer array.
        position_chunks = []
        color_chunks = []  # Need to store colors point-wise so the single Line can have multiple colors.

        position_buffer_break = np.array([[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]], dtype=np.float32)
        color_buffer_break = np.array([[0, 0, 0, 0]], dtype=np.float32)

        # For each satellite, generate the dense trajectory from the spline and then create the corresponding
        # color_chunk. Then append these to the chunk lists.
        for name, satellite in self.sim.satellites.items():
            self.positions[name] = self.sim.splines["positions"][name](self.dense_times)
            self.positions[name] = self.positions[name].astype(np.float32)  # Data type needed by gfx.Geometry.

            color = np.array(gfx.Color(satellite.color), dtype=np.float32)
            color_chunk = np.tile(color, (len(self.positions[name]) + 1, 1))  # +1 to account for flex positions.

            position_chunks.append(np.vstack([self.positions[name], position_buffer_break]))
            color_chunks.append(np.vstack([color_chunk, color_buffer_break]))

        # Create the full buffer and then line object from the chunk lists. We store the buffer here because it is
        # needed later for dynamic horizon updates.
        orbit_buffer = np.vstack(position_chunks)
        color_buffer = np.vstack(color_chunks)
        self.objects["orbits_polyline"] = gfx.Line(
            geometry=gfx.Geometry(positions=orbit_buffer, colors=color_buffer),
            material=gfx.LineMaterial(color_mode="vertex")
        )

        self._scene.add(self.objects["orbits_polyline"])
        self.orbit_buffer = orbit_buffer

        # Repeat the above process but this time with a pygfx.Points object in order to render the satellites
        # themselves.
        satellite_chunks = []
        color_chunks = []

        for name, satellite in self.sim.satellites.items():
            satellite_chunks.append(self.sim.splines["positions"][name](0).astype(np.float32))
            color_chunks.append(np.array(gfx.Color(satellite.color)).astype(np.float32))

        satellite_buffer = np.vstack(satellite_chunks)
        color_buffer = np.vstack(color_chunks)

        self.objects["satellite_points"] = gfx.Points(
            geometry=gfx.Geometry(positions=satellite_buffer, colors=color_buffer),
            material=gfx.PointsMaterial(size=12, color_mode="vertex")
        )
        self._scene.add(self.objects["satellite_points"])
        self.satellite_buffer = satellite_buffer

        # Add the pygfx render to a qt widget.
        layout = PySide6.QtWidgets.QVBoxLayout(self)
        layout.addWidget(self._canvas)

    def animate(self):
        """
        One frame of the animation loop.
        """

        earth_rot = 7.292115e-5  # Mean rotation rate of the Earth in rad/s.

        # Update the Earth's rotation. Note that this is a simple mean precession linear progression and doesn't contain
        # nutation.
        self.objects["earth"].local.rotation = la.quat_mul(
            self.base_earth_rotation,
            la.quat_from_axis_angle((0, 1, 0), self.sim.sim_time * earth_rot),
        )

        # This is the update loop for all of moving geometry. This includes satellites as well as orbits (since when
        # orbits are set to have a finite horizon the portion of the orbit drawn is constantly changing).
        #   For the orbits, the basic premise is that rather than recreate the Line object holding all
        # the orbits we just flush and then rebuild its Geometry attribute's internal vertex data which is simply a
        # numpy array. For each satellite (although in this case we use only their trajectory via this classes'
        # position attribute) we determine which indices range corresponds to the current horizon flag. In the
        # orbit_buffer we then only set these indices to their actual position values and leave the rest as NaN.
        #   Each chunk also has an extra buffer row added in for a "flex position". This allows the insertion of an
        # extra dynamically-computed vertex computed every frame by calling the position spline. This way the orbit
        # exactly matches up the with the RSO when the horizon is set to "past" and doesn't jitter.
        #   Satellites are updated using similar logic.
        base_orbit_index = 0  # Where vertically in the buffer we are.
        base_satellite_index = 0

        self.orbit_buffer[:, :] = np.nan  # Flush the buffer.
        self.satellite_buffer[:, :] = np.nan

        for name in self.sim.satellites.keys():
            if self.orbit_display_mode != "rso":
                if self.sim.satellite_display_flags[name]:
                    match self.horizon_display_mode:
                        case "none":
                            lower_index = 0
                            upper_index = 0
                        case "period":
                            position = self.sim.splines["positions"][name](self.sim.sim_time) * 1000
                            velocity = self.sim.splines["velocities"][name](self.sim.sim_time) * 1000
                            grav_param = self.sim.satellites[name].orbit.grav_param

                            sm_axis = -grav_param / (
                                np.linalg.norm(velocity) ** 2 / 2 - grav_param / np.linalg.norm(position)) / 2
                            if sm_axis < 0:
                                sm_axis *= -1
                            period = 2 * np.pi * np.sqrt(sm_axis ** 3 / grav_param)

                            lower_index = np.searchsorted(self.dense_times, self.sim.sim_time - period)
                            upper_index = np.searchsorted(self.dense_times, self.sim.sim_time + period)
                        case "full":
                            lower_index = 0
                            upper_index = len(self.dense_times)
                        case "past":
                            lower_index = 0
                            upper_index = np.searchsorted(self.dense_times, self.sim.sim_time)
                        case "hour":
                            lower_index = np.searchsorted(self.dense_times, self.sim.sim_time - 60 * 60)
                            upper_index = np.searchsorted(self.dense_times, self.sim.sim_time + 60 * 60)
                        case "half_day":
                            lower_index = np.searchsorted(self.dense_times, self.sim.sim_time - 60 * 60 * 12)
                            upper_index = np.searchsorted(self.dense_times, self.sim.sim_time + 60 * 60 * 12)
                        case "day":
                            lower_index = np.searchsorted(self.dense_times, self.sim.sim_time - 60 * 60 * 24)
                            upper_index = np.searchsorted(self.dense_times, self.sim.sim_time + 60 * 60 * 24)
                        case "custom":
                            lower_index = np.searchsorted(self.dense_times, self.sim.sim_time - self.custom_horizon)
                            upper_index = np.searchsorted(self.dense_times, self.sim.sim_time + self.custom_horizon)

                    # For the portion of the orbit_buffer corresponding to this satellite's trajectory (found via
                    # base_index) set the rows between lower and upper index to their actual values.
                    self.orbit_buffer[base_orbit_index + lower_index: base_orbit_index + upper_index, :] = (
                        self.positions[name][lower_index:upper_index, :]
                    )
                    if self.horizon_display_mode == "past":  # Need flex position to prevent jitter.
                        self.orbit_buffer[base_orbit_index + upper_index, :] = (
                            self.sim.splines["positions"][name](self.sim.sim_time).astype(np.float32)
                        )  # Add flex position.
                base_orbit_index += self.positions[name].shape[0] + 2  # Move to start of next satellite's trajectory.

            # Update the satellite's positions using similar logic as with the orbits.
            if self.orbit_display_mode != "traj":
                if self.sim.satellite_display_flags[name]:
                    self.satellite_buffer[base_satellite_index, :] = (
                        self.sim.splines["positions"][name](self.sim.sim_time).astype(np.float32)
                    )
                base_satellite_index += 1

        # Rebuild buffers.
        self.objects["orbits_polyline"].geometry.positions.set_data(
           self.orbit_buffer
        )
        self.objects["satellite_points"].geometry.positions.set_data(
            self.satellite_buffer
        )

        # Standard rendering code, also orients the camera. If the camera is supposed to be orbiting the Earth we just
        # have it orbit (0, 0, 0). However, if it is orbiting a satellite we instead shift the entire pygfx.Scene (as
        # the  scene is itself an object located in the frame of pygfx.Canvas) so that that object lives at (0, 0, 0).
        # This is done because the logic of pygfx.OrbitController breaks when trying to follow a moving target.
        if self.sim.focus is None:
            target = np.array([0, 0, 0])
        else:
            target = self.sim.splines["positions"][self.sim.focus](self.sim.sim_time)

        # Must update before render() call.
        self._scene.local.position = tuple(-target)
        self._camera.show_pos((0, 0, 0), up=(0, 0, 1))

        self._renderer.render(self._scene, self._camera)
        self._canvas.request_draw(self.animate)  # Recursive call to start rendering loop.
